// Code generated by MockGen. DO NOT EDIT.
// Source: content_builders.go
//
// Generated by this command:
//
//	mockgen -source=content_builders.go -destination=../../mocks/contentbuilders/forget_password_content_builder.go -package=mockcontentbuilders -exclude_interfaces=VerifyEmailContentBuilder,NewMessageContentBuilder
//

// Package mockcontentbuilders is a generated GoMock package.
package mockcontentbuilders

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockForgetPasswordContentBuilder is a mock of ForgetPasswordContentBuilder interface.
type MockForgetPasswordContentBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockForgetPasswordContentBuilderMockRecorder
	isgomock struct{}
}

// MockForgetPasswordContentBuilderMockRecorder is the mock recorder for MockForgetPasswordContentBuilder.
type MockForgetPasswordContentBuilderMockRecorder struct {
	mock *MockForgetPasswordContentBuilder
}

// NewMockForgetPasswordContentBuilder creates a new mock instance.
func NewMockForgetPasswordContentBuilder(ctrl *gomock.Controller) *MockForgetPasswordContentBuilder {
	mock := &MockForgetPasswordContentBuilder{ctrl: ctrl}
	mock.recorder = &MockForgetPasswordContentBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForgetPasswordContentBuilder) EXPECT() *MockForgetPasswordContentBuilderMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockForgetPasswordContentBuilder) Body(ctx context.Context, user domains.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Body indicates an expected call of Body.
func (mr *MockForgetPasswordContentBuilderMockRecorder) Body(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockForgetPasswordContentBuilder)(nil).Body), ctx, user)
}

// Subject mocks base method.
func (m *MockForgetPasswordContentBuilder) Subject() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockForgetPasswordContentBuilderMockRecorder) Subject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockForgetPasswordContentBuilder)(nil).Subject))
}
