// Code generated by MockGen. DO NOT EDIT.
// Source: content_builders.go
//
// Generated by this command:
//
//	mockgen -source=content_builders.go -destination=../../mocks/contentbuilders/new_message_content_builder.go -package=mockcontentbuilders -exclude_interfaces=VerifyEmailContentBuilder,ForgetPasswordContentBuilder
//

// Package mockcontentbuilders is a generated GoMock package.
package mockcontentbuilders

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockNewMessageContentBuilder is a mock of NewMessageContentBuilder interface.
type MockNewMessageContentBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockNewMessageContentBuilderMockRecorder
	isgomock struct{}
}

// MockNewMessageContentBuilderMockRecorder is the mock recorder for MockNewMessageContentBuilder.
type MockNewMessageContentBuilderMockRecorder struct {
	mock *MockNewMessageContentBuilder
}

// NewMockNewMessageContentBuilder creates a new mock instance.
func NewMockNewMessageContentBuilder(ctrl *gomock.Controller) *MockNewMessageContentBuilder {
	mock := &MockNewMessageContentBuilder{ctrl: ctrl}
	mock.recorder = &MockNewMessageContentBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewMessageContentBuilder) EXPECT() *MockNewMessageContentBuilderMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockNewMessageContentBuilder) Body(ctx context.Context, message domains.Message, chat domains.Chat) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body", ctx, message, chat)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Body indicates an expected call of Body.
func (mr *MockNewMessageContentBuilderMockRecorder) Body(ctx, message, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockNewMessageContentBuilder)(nil).Body), ctx, message, chat)
}

// Subject mocks base method.
func (m *MockNewMessageContentBuilder) Subject() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockNewMessageContentBuilderMockRecorder) Subject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockNewMessageContentBuilder)(nil).Subject))
}
