###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "alexqwerty35@yandex.ru",
  "username": "testDemos",
  "password": "SomeTestP@ssword228"
}

###

GET http://localhost:8080/users?username=test&limit=1&offset=0
Content-Type: application/json

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "alexqwerty35@yandex.ru",
  "password": "SomeTestP@ssword228"
}

###

GET http://localhost:8080/users/1
Content-Type: application/json

###

GET http://localhost:8080/users/me
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjY1MjYyODAsInZhbHVlIjoxfQ.NHYO8VPzsFqrZfqSPyvOkLqstcQsP3HVysEkxyaTOTk
