###

POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "alexqwerty35@yandex.ru",
  "username": "testDemos",
  "password": "SomeTestP@ssword228"
}

###

GET http://localhost:8080/users?username=test&limit=1&offset=0
Content-Type: application/json

###

POST http://localhost:8080/sessions
Content-Type: application/json

{
  "login": "alexqwerty35@yandex.ru",
  "password": "SomeTestP@ssword228"
}

###

GET http://localhost:8080/users/8
Content-Type: application/json

###

GET http://localhost:8080/users/me
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjcyNjAzOTYsInZhbHVlIjo4fQ.awOV0Qw11xlih47h-yVvTB2Se2EU_F_T0L4nbeNFT0E

###

DELETE http://localhost:8080/sessions
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjcyNjAzOTYsInZhbHVlIjo4fQ.awOV0Qw11xlih47h-yVvTB2Se2EU_F_T0L4nbeNFT0E

###

PUT http://localhost:8080/sessions
Content-Type: application/json
Cookie: refreshToken=ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxlSEFpT2pFM05qYzRNVE15TWpJc0luWmhiSFZsSWpvaVpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNYTkpibEkxWTBOSk5rbHJjRmhXUTBvNUxtVjVTbXhsU0VGcFQycEZNMDVxWTNsTlJHdDZUV3BKYzBsdVdtaGlTRlpzU1dwdk5HWlJMa3hQVFRaNGVrWlRjRzFOTFZWS1lVaHJOMEZMTVRKRmJHaEZhSFZFWXpkVWRrbHRaRTFXWmpkT05ITWlmUS5lbWRQVnJZR2tQSWdLWlRycUZVUXFUSTRvNDhvbnBqRUQ2Y0hHX0VLZHhV

###

PUT http://localhost:8080/users/me
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzc1Mzk2NzIsInZhbHVlIjozfQ.q_liXR45TjXMdx5AQlugIgn0YPab0FpmIfDT_BM3HJE

{
  "username": "d3m0s"
}

###

POST http://localhost:8080/users/email/verify
Content-Type: application/json

{
  "email": "alexqwerty35@yandex.ru"
}

###

POST http://localhost:8080/users/email/verify/Nw
Content-Type: application/json

###

POST http://localhost:8080/users/password/change
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjcyMDk1NDgsInZhbHVlIjo4fQ.CAFCH8zxXcyk0irbf5XOa0oVDF1Osf25rUCgBnFZRKY

{
  "oldPassword": "SomeTestP@ssword228",
  "newPassword": "SomeTestP@ssword228Changed"
}

###

POST http://localhost:8080/users/password/forget
Content-Type: application/json

{
  "email": "alexqwerty35@yandex.ru"
}

###

POST http://localhost:8080/users/password/forget/Nw
Content-Type: application/json

{
  "newPassword": "SomeTestP@ssword228"
}

###

GET http://localhost:8080/ws
Content-Type: application/json
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Version: 13
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjgxMjY3MTEsInZhbHVlIjo4fQ.HeO8C4iuZKxeC40kvHYJ731NqrwWFX5VFep5Watmqms

###

POST http://localhost:8080/chats
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjgxMzg3NzksInZhbHVlIjo5fQ.QGlWINTO24rNAmukfg_b5onM_ECBZjWYP4mjSQLBH-8

{
  "type": "private",
  "members": [
    {
      "id": 12
    }
  ]
}

###

GET http://localhost:8080/chats?limit=3&offset=0
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjgxMzk4NjksInZhbHVlIjo4fQ.EDC1g59iOI50AF79i1mnPux0qz0bf1e9l0tao0o8GeM


###

GET http://localhost:8080/chats/1/messages?limit=2&offset=0
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjgxMzk4NjksInZhbHVlIjo4fQ.EDC1g59iOI50AF79i1mnPux0qz0bf1e9l0tao0o8GeM

