// Code generated by MockGen. DO NOT EDIT.
// Source: controllers.go
//
// Generated by this command:
//
//	mockgen -source=controllers.go -destination=../../mocks/controllers/ws_broadcaster.go -package=mockcontrollers -exclude_interfaces=Controller
//

// Package mockcontrollers is a generated GoMock package.
package mockcontrollers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWSBroadcaster is a mock of WSBroadcaster interface.
type MockWSBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockWSBroadcasterMockRecorder
	isgomock struct{}
}

// MockWSBroadcasterMockRecorder is the mock recorder for MockWSBroadcaster.
type MockWSBroadcasterMockRecorder struct {
	mock *MockWSBroadcaster
}

// NewMockWSBroadcaster creates a new mock instance.
func NewMockWSBroadcaster(ctrl *gomock.Controller) *MockWSBroadcaster {
	mock := &MockWSBroadcaster{ctrl: ctrl}
	mock.recorder = &MockWSBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSBroadcaster) EXPECT() *MockWSBroadcasterMockRecorder {
	return m.recorder
}

// BroadcastMessageDeleted mocks base method.
func (m *MockWSBroadcaster) BroadcastMessageDeleted(ctx context.Context, chatID, messageID, userID uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastMessageDeleted", ctx, chatID, messageID, userID)
}

// BroadcastMessageDeleted indicates an expected call of BroadcastMessageDeleted.
func (mr *MockWSBroadcasterMockRecorder) BroadcastMessageDeleted(ctx, chatID, messageID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMessageDeleted", reflect.TypeOf((*MockWSBroadcaster)(nil).BroadcastMessageDeleted), ctx, chatID, messageID, userID)
}

// BroadcastMessageEdited mocks base method.
func (m *MockWSBroadcaster) BroadcastMessageEdited(ctx context.Context, chatID, messageID, userID uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastMessageEdited", ctx, chatID, messageID, userID)
}

// BroadcastMessageEdited indicates an expected call of BroadcastMessageEdited.
func (mr *MockWSBroadcasterMockRecorder) BroadcastMessageEdited(ctx, chatID, messageID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMessageEdited", reflect.TypeOf((*MockWSBroadcaster)(nil).BroadcastMessageEdited), ctx, chatID, messageID, userID)
}

// BroadcastReactionAdded mocks base method.
func (m *MockWSBroadcaster) BroadcastReactionAdded(ctx context.Context, messageID, userID, reactionID uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastReactionAdded", ctx, messageID, userID, reactionID)
}

// BroadcastReactionAdded indicates an expected call of BroadcastReactionAdded.
func (mr *MockWSBroadcasterMockRecorder) BroadcastReactionAdded(ctx, messageID, userID, reactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastReactionAdded", reflect.TypeOf((*MockWSBroadcaster)(nil).BroadcastReactionAdded), ctx, messageID, userID, reactionID)
}

// BroadcastReactionRemoved mocks base method.
func (m *MockWSBroadcaster) BroadcastReactionRemoved(ctx context.Context, messageID, userID, reactionID uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastReactionRemoved", ctx, messageID, userID, reactionID)
}

// BroadcastReactionRemoved indicates an expected call of BroadcastReactionRemoved.
func (mr *MockWSBroadcasterMockRecorder) BroadcastReactionRemoved(ctx, messageID, userID, reactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastReactionRemoved", reflect.TypeOf((*MockWSBroadcaster)(nil).BroadcastReactionRemoved), ctx, messageID, userID, reactionID)
}

// SendMessageDeletedToUser mocks base method.
func (m *MockWSBroadcaster) SendMessageDeletedToUser(ctx context.Context, chatID, messageID, userID uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendMessageDeletedToUser", ctx, chatID, messageID, userID)
}

// SendMessageDeletedToUser indicates an expected call of SendMessageDeletedToUser.
func (mr *MockWSBroadcasterMockRecorder) SendMessageDeletedToUser(ctx, chatID, messageID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageDeletedToUser", reflect.TypeOf((*MockWSBroadcaster)(nil).SendMessageDeletedToUser), ctx, chatID, messageID, userID)
}
