// Code generated by MockGen. DO NOT EDIT.
// Source: controllers.go
//
// Generated by this command:
//
//	mockgen -source=controllers.go -destination=../../mocks/controllers/ws_broadcaster.go -package=mockcontrollers -exclude_interfaces=Controller
//

// Package mockcontrollers is a generated GoMock package.
package mockcontrollers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWSBroadcaster is a mock of WSBroadcaster interface.
type MockWSBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockWSBroadcasterMockRecorder
	isgomock struct{}
}

// MockWSBroadcasterMockRecorder is the mock recorder for MockWSBroadcaster.
type MockWSBroadcasterMockRecorder struct {
	mock *MockWSBroadcaster
}

// NewMockWSBroadcaster creates a new mock instance.
func NewMockWSBroadcaster(ctrl *gomock.Controller) *MockWSBroadcaster {
	mock := &MockWSBroadcaster{ctrl: ctrl}
	mock.recorder = &MockWSBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSBroadcaster) EXPECT() *MockWSBroadcasterMockRecorder {
	return m.recorder
}

// BroadcastMessageDeleted mocks base method.
func (m *MockWSBroadcaster) BroadcastMessageDeleted(ctx context.Context, chatID, messageID, senderID uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastMessageDeleted", ctx, chatID, messageID, senderID)
}

// BroadcastMessageDeleted indicates an expected call of BroadcastMessageDeleted.
func (mr *MockWSBroadcasterMockRecorder) BroadcastMessageDeleted(ctx, chatID, messageID, senderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMessageDeleted", reflect.TypeOf((*MockWSBroadcaster)(nil).BroadcastMessageDeleted), ctx, chatID, messageID, senderID)
}
