// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/auth_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/khodfeltschat/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUseCases is a mock of AuthUseCases interface.
type MockAuthUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCasesMockRecorder
	isgomock struct{}
}

// MockAuthUseCasesMockRecorder is the mock recorder for MockAuthUseCases.
type MockAuthUseCasesMockRecorder struct {
	mock *MockAuthUseCases
}

// NewMockAuthUseCases creates a new mock instance.
func NewMockAuthUseCases(ctrl *gomock.Controller) *MockAuthUseCases {
	mock := &MockAuthUseCases{ctrl: ctrl}
	mock.recorder = &MockAuthUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCases) EXPECT() *MockAuthUseCasesMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockAuthUseCases) ChangePassword(ctx context.Context, accessToken, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, accessToken, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthUseCasesMockRecorder) ChangePassword(ctx, accessToken, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthUseCases)(nil).ChangePassword), ctx, accessToken, oldPassword, newPassword)
}

// ForgetPassword mocks base method.
func (m *MockAuthUseCases) ForgetPassword(ctx context.Context, forgetPasswordToken, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgetPassword", ctx, forgetPasswordToken, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgetPassword indicates an expected call of ForgetPassword.
func (mr *MockAuthUseCasesMockRecorder) ForgetPassword(ctx, forgetPasswordToken, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgetPassword", reflect.TypeOf((*MockAuthUseCases)(nil).ForgetPassword), ctx, forgetPasswordToken, newPassword)
}

// LoginUser mocks base method.
func (m *MockAuthUseCases) LoginUser(ctx context.Context, userData domains.LoginDTO) (*domains.TokensDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, userData)
	ret0, _ := ret[0].(*domains.TokensDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockAuthUseCasesMockRecorder) LoginUser(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockAuthUseCases)(nil).LoginUser), ctx, userData)
}

// LogoutUser mocks base method.
func (m *MockAuthUseCases) LogoutUser(ctx context.Context, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutUser", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutUser indicates an expected call of LogoutUser.
func (mr *MockAuthUseCasesMockRecorder) LogoutUser(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutUser", reflect.TypeOf((*MockAuthUseCases)(nil).LogoutUser), ctx, accessToken)
}

// RefreshTokens mocks base method.
func (m *MockAuthUseCases) RefreshTokens(ctx context.Context, refreshToken string) (*domains.TokensDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, refreshToken)
	ret0, _ := ret[0].(*domains.TokensDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthUseCasesMockRecorder) RefreshTokens(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthUseCases)(nil).RefreshTokens), ctx, refreshToken)
}

// RegisterUser mocks base method.
func (m *MockAuthUseCases) RegisterUser(ctx context.Context, userData domains.RegisterDTO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, userData)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthUseCasesMockRecorder) RegisterUser(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthUseCases)(nil).RegisterUser), ctx, userData)
}

// SendForgetPasswordMessage mocks base method.
func (m *MockAuthUseCases) SendForgetPasswordMessage(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendForgetPasswordMessage", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendForgetPasswordMessage indicates an expected call of SendForgetPasswordMessage.
func (mr *MockAuthUseCasesMockRecorder) SendForgetPasswordMessage(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendForgetPasswordMessage", reflect.TypeOf((*MockAuthUseCases)(nil).SendForgetPasswordMessage), ctx, email)
}

// SendVerifyEmailMessage mocks base method.
func (m *MockAuthUseCases) SendVerifyEmailMessage(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerifyEmailMessage", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerifyEmailMessage indicates an expected call of SendVerifyEmailMessage.
func (mr *MockAuthUseCasesMockRecorder) SendVerifyEmailMessage(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerifyEmailMessage", reflect.TypeOf((*MockAuthUseCases)(nil).SendVerifyEmailMessage), ctx, email)
}

// VerifyUserEmail mocks base method.
func (m *MockAuthUseCases) VerifyUserEmail(ctx context.Context, verifyEmailToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserEmail", ctx, verifyEmailToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserEmail indicates an expected call of VerifyUserEmail.
func (mr *MockAuthUseCasesMockRecorder) VerifyUserEmail(ctx, verifyEmailToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserEmail", reflect.TypeOf((*MockAuthUseCases)(nil).VerifyUserEmail), ctx, verifyEmailToken)
}
