// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/chats_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsUseCases is a mock of ChatsUseCases interface.
type MockChatsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockChatsUseCasesMockRecorder
	isgomock struct{}
}

// MockChatsUseCasesMockRecorder is the mock recorder for MockChatsUseCases.
type MockChatsUseCasesMockRecorder struct {
	mock *MockChatsUseCases
}

// NewMockChatsUseCases creates a new mock instance.
func NewMockChatsUseCases(ctrl *gomock.Controller) *MockChatsUseCases {
	mock := &MockChatsUseCases{ctrl: ctrl}
	mock.recorder = &MockChatsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsUseCases) EXPECT() *MockChatsUseCasesMockRecorder {
	return m.recorder
}

// GetChatMembers mocks base method.
func (m *MockChatsUseCases) GetChatMembers(chatID string) ([]domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembers", chatID)
	ret0, _ := ret[0].([]domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembers indicates an expected call of GetChatMembers.
func (mr *MockChatsUseCasesMockRecorder) GetChatMembers(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembers", reflect.TypeOf((*MockChatsUseCases)(nil).GetChatMembers), chatID)
}
