// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/chats_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,MessagesUseCases,NotificationsUseCases,SettingsUseCases,WebPushSubscriptionsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsUseCases is a mock of ChatsUseCases interface.
type MockChatsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockChatsUseCasesMockRecorder
	isgomock struct{}
}

// MockChatsUseCasesMockRecorder is the mock recorder for MockChatsUseCases.
type MockChatsUseCasesMockRecorder struct {
	mock *MockChatsUseCases
}

// NewMockChatsUseCases creates a new mock instance.
func NewMockChatsUseCases(ctrl *gomock.Controller) *MockChatsUseCases {
	mock := &MockChatsUseCases{ctrl: ctrl}
	mock.recorder = &MockChatsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsUseCases) EXPECT() *MockChatsUseCasesMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatsUseCases) CreateChat(ctx context.Context, chat domains.Chat) (*domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chat)
	ret0, _ := ret[0].(*domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsUseCasesMockRecorder) CreateChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsUseCases)(nil).CreateChat), ctx, chat)
}

// GetChatMembers mocks base method.
func (m *MockChatsUseCases) GetChatMembers(ctx context.Context, chatID uint64) ([]domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembers", ctx, chatID)
	ret0, _ := ret[0].([]domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembers indicates an expected call of GetChatMembers.
func (mr *MockChatsUseCasesMockRecorder) GetChatMembers(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembers", reflect.TypeOf((*MockChatsUseCases)(nil).GetChatMembers), ctx, chatID)
}

// GetUserChats mocks base method.
func (m *MockChatsUseCases) GetUserChats(ctx context.Context, userID uint64, pagination *domains.Pagination) ([]domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", ctx, userID, pagination)
	ret0, _ := ret[0].([]domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatsUseCasesMockRecorder) GetUserChats(ctx, userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatsUseCases)(nil).GetUserChats), ctx, userID, pagination)
}
