// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/file_storage_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,ChatsUseCases,MessagesUseCases,NotificationsUseCases,SettingsUseCases,WebPushSubscriptionsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStorageUseCases is a mock of FileStorageUseCases interface.
type MockFileStorageUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageUseCasesMockRecorder
	isgomock struct{}
}

// MockFileStorageUseCasesMockRecorder is the mock recorder for MockFileStorageUseCases.
type MockFileStorageUseCasesMockRecorder struct {
	mock *MockFileStorageUseCases
}

// NewMockFileStorageUseCases creates a new mock instance.
func NewMockFileStorageUseCases(ctrl *gomock.Controller) *MockFileStorageUseCases {
	mock := &MockFileStorageUseCases{ctrl: ctrl}
	mock.recorder = &MockFileStorageUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorageUseCases) EXPECT() *MockFileStorageUseCasesMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStorageUseCases) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageUseCasesMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorageUseCases)(nil).Delete), ctx, path)
}

// Download mocks base method.
func (m *MockFileStorageUseCases) Download(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockFileStorageUseCasesMockRecorder) Download(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileStorageUseCases)(nil).Download), ctx, path)
}

// Upload mocks base method.
func (m *MockFileStorageUseCases) Upload(ctx context.Context, path string, data io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, path, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageUseCasesMockRecorder) Upload(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorageUseCases)(nil).Upload), ctx, path, data)
}
