// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/messages_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,ChatsUseCases,NotificationsUseCases,SettingsUseCases,PushSubscriptionsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesUseCases is a mock of MessagesUseCases interface.
type MockMessagesUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesUseCasesMockRecorder
	isgomock struct{}
}

// MockMessagesUseCasesMockRecorder is the mock recorder for MockMessagesUseCases.
type MockMessagesUseCasesMockRecorder struct {
	mock *MockMessagesUseCases
}

// NewMockMessagesUseCases creates a new mock instance.
func NewMockMessagesUseCases(ctrl *gomock.Controller) *MockMessagesUseCases {
	mock := &MockMessagesUseCases{ctrl: ctrl}
	mock.recorder = &MockMessagesUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesUseCases) EXPECT() *MockMessagesUseCasesMockRecorder {
	return m.recorder
}

// GetChatMessages mocks base method.
func (m *MockMessagesUseCases) GetChatMessages(ctx context.Context, userID, chatID uint64, pagination *domains.Pagination) ([]domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessages", ctx, userID, chatID, pagination)
	ret0, _ := ret[0].([]domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessages indicates an expected call of GetChatMessages.
func (mr *MockMessagesUseCasesMockRecorder) GetChatMessages(ctx, userID, chatID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessages", reflect.TypeOf((*MockMessagesUseCases)(nil).GetChatMessages), ctx, userID, chatID, pagination)
}

// GetMessageByID mocks base method.
func (m *MockMessagesUseCases) GetMessageByID(ctx context.Context, userID, messageID uint64) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, userID, messageID)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessagesUseCasesMockRecorder) GetMessageByID(ctx, userID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessagesUseCases)(nil).GetMessageByID), ctx, userID, messageID)
}

// SaveMessage mocks base method.
func (m *MockMessagesUseCases) SaveMessage(ctx context.Context, message domains.Message) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessagesUseCasesMockRecorder) SaveMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessagesUseCases)(nil).SaveMessage), ctx, message)
}
