// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/notifications_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,ChatsUseCases,MessagesUseCases,AuthUseCases,SettingsUseCases,WebPushSubscriptionsUseCases,FileStorageUseCases,ReactionsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationsUseCases is a mock of NotificationsUseCases interface.
type MockNotificationsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationsUseCasesMockRecorder
	isgomock struct{}
}

// MockNotificationsUseCasesMockRecorder is the mock recorder for MockNotificationsUseCases.
type MockNotificationsUseCasesMockRecorder struct {
	mock *MockNotificationsUseCases
}

// NewMockNotificationsUseCases creates a new mock instance.
func NewMockNotificationsUseCases(ctrl *gomock.Controller) *MockNotificationsUseCases {
	mock := &MockNotificationsUseCases{ctrl: ctrl}
	mock.recorder = &MockNotificationsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationsUseCases) EXPECT() *MockNotificationsUseCasesMockRecorder {
	return m.recorder
}

// SendForgetPasswordMessage mocks base method.
func (m *MockNotificationsUseCases) SendForgetPasswordMessage(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendForgetPasswordMessage", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendForgetPasswordMessage indicates an expected call of SendForgetPasswordMessage.
func (mr *MockNotificationsUseCasesMockRecorder) SendForgetPasswordMessage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendForgetPasswordMessage", reflect.TypeOf((*MockNotificationsUseCases)(nil).SendForgetPasswordMessage), ctx, userID)
}

// SendNewMessageByEmail mocks base method.
func (m *MockNotificationsUseCases) SendNewMessageByEmail(ctx context.Context, userID uint64, payload domains.NewMessagePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNewMessageByEmail", ctx, userID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNewMessageByEmail indicates an expected call of SendNewMessageByEmail.
func (mr *MockNotificationsUseCasesMockRecorder) SendNewMessageByEmail(ctx, userID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNewMessageByEmail", reflect.TypeOf((*MockNotificationsUseCases)(nil).SendNewMessageByEmail), ctx, userID, payload)
}

// SendNewMessageByWebPush mocks base method.
func (m *MockNotificationsUseCases) SendNewMessageByWebPush(ctx context.Context, userID uint64, payload domains.NewMessagePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNewMessageByWebPush", ctx, userID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNewMessageByWebPush indicates an expected call of SendNewMessageByWebPush.
func (mr *MockNotificationsUseCasesMockRecorder) SendNewMessageByWebPush(ctx, userID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNewMessageByWebPush", reflect.TypeOf((*MockNotificationsUseCases)(nil).SendNewMessageByWebPush), ctx, userID, payload)
}

// SendVerifyEmailMessage mocks base method.
func (m *MockNotificationsUseCases) SendVerifyEmailMessage(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerifyEmailMessage", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerifyEmailMessage indicates an expected call of SendVerifyEmailMessage.
func (mr *MockNotificationsUseCasesMockRecorder) SendVerifyEmailMessage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerifyEmailMessage", reflect.TypeOf((*MockNotificationsUseCases)(nil).SendVerifyEmailMessage), ctx, userID)
}
