// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/push_subscriptions_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,ChatsUseCases,MessagesUseCases,NotificationsUseCases,SettingsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockPushSubscriptionsUseCases is a mock of PushSubscriptionsUseCases interface.
type MockPushSubscriptionsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionsUseCasesMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionsUseCasesMockRecorder is the mock recorder for MockPushSubscriptionsUseCases.
type MockPushSubscriptionsUseCasesMockRecorder struct {
	mock *MockPushSubscriptionsUseCases
}

// NewMockPushSubscriptionsUseCases creates a new mock instance.
func NewMockPushSubscriptionsUseCases(ctrl *gomock.Controller) *MockPushSubscriptionsUseCases {
	mock := &MockPushSubscriptionsUseCases{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionsUseCases) EXPECT() *MockPushSubscriptionsUseCasesMockRecorder {
	return m.recorder
}

// CreatePushSubscription mocks base method.
func (m *MockPushSubscriptionsUseCases) CreatePushSubscription(ctx context.Context, subscription domains.PushSubscription) (*domains.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushSubscription", ctx, subscription)
	ret0, _ := ret[0].(*domains.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePushSubscription indicates an expected call of CreatePushSubscription.
func (mr *MockPushSubscriptionsUseCasesMockRecorder) CreatePushSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushSubscription", reflect.TypeOf((*MockPushSubscriptionsUseCases)(nil).CreatePushSubscription), ctx, subscription)
}

// DeletePushSubscription mocks base method.
func (m *MockPushSubscriptionsUseCases) DeletePushSubscription(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePushSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePushSubscription indicates an expected call of DeletePushSubscription.
func (mr *MockPushSubscriptionsUseCasesMockRecorder) DeletePushSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePushSubscription", reflect.TypeOf((*MockPushSubscriptionsUseCases)(nil).DeletePushSubscription), ctx, id)
}

// GetPushSubscriptionsByUserID mocks base method.
func (m *MockPushSubscriptionsUseCases) GetPushSubscriptionsByUserID(ctx context.Context, userID uint64) ([]domains.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domains.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushSubscriptionsByUserID indicates an expected call of GetPushSubscriptionsByUserID.
func (mr *MockPushSubscriptionsUseCasesMockRecorder) GetPushSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushSubscriptionsByUserID", reflect.TypeOf((*MockPushSubscriptionsUseCases)(nil).GetPushSubscriptionsByUserID), ctx, userID)
}

// SendPushNotification mocks base method.
func (m *MockPushSubscriptionsUseCases) SendPushNotification(ctx context.Context, subscription domains.PushSubscription, message domains.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPushNotification", ctx, subscription, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPushNotification indicates an expected call of SendPushNotification.
func (mr *MockPushSubscriptionsUseCasesMockRecorder) SendPushNotification(ctx, subscription, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPushNotification", reflect.TypeOf((*MockPushSubscriptionsUseCases)(nil).SendPushNotification), ctx, subscription, message)
}
