// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/reactions_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,ChatsUseCases,MessagesUseCases,NotificationsUseCases,SettingsUseCases,WebPushSubscriptionsUseCases,FileStorageUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockReactionsUseCases is a mock of ReactionsUseCases interface.
type MockReactionsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockReactionsUseCasesMockRecorder
	isgomock struct{}
}

// MockReactionsUseCasesMockRecorder is the mock recorder for MockReactionsUseCases.
type MockReactionsUseCasesMockRecorder struct {
	mock *MockReactionsUseCases
}

// NewMockReactionsUseCases creates a new mock instance.
func NewMockReactionsUseCases(ctrl *gomock.Controller) *MockReactionsUseCases {
	mock := &MockReactionsUseCases{ctrl: ctrl}
	mock.recorder = &MockReactionsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReactionsUseCases) EXPECT() *MockReactionsUseCasesMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockReactionsUseCases) AddReaction(ctx context.Context, dto domains.MessageReactionDTO) (uint64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", ctx, dto)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockReactionsUseCasesMockRecorder) AddReaction(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockReactionsUseCases)(nil).AddReaction), ctx, dto)
}

// AttachReaction mocks base method.
func (m *MockReactionsUseCases) AttachReaction(ctx context.Context, msg *domains.Message) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachReaction", ctx, msg)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachReaction indicates an expected call of AttachReaction.
func (mr *MockReactionsUseCasesMockRecorder) AttachReaction(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachReaction", reflect.TypeOf((*MockReactionsUseCases)(nil).AttachReaction), ctx, msg)
}

// AttachReactions mocks base method.
func (m *MockReactionsUseCases) AttachReactions(ctx context.Context, msgs []domains.Message) ([]domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachReactions", ctx, msgs)
	ret0, _ := ret[0].([]domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachReactions indicates an expected call of AttachReactions.
func (mr *MockReactionsUseCasesMockRecorder) AttachReactions(ctx, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachReactions", reflect.TypeOf((*MockReactionsUseCases)(nil).AttachReactions), ctx, msgs)
}

// ListReactions mocks base method.
func (m *MockReactionsUseCases) ListReactions(ctx context.Context) ([]domains.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReactions", ctx)
	ret0, _ := ret[0].([]domains.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReactions indicates an expected call of ListReactions.
func (mr *MockReactionsUseCasesMockRecorder) ListReactions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReactions", reflect.TypeOf((*MockReactionsUseCases)(nil).ListReactions), ctx)
}

// RemoveReaction mocks base method.
func (m *MockReactionsUseCases) RemoveReaction(ctx context.Context, dto domains.MessageReactionDTO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReaction", ctx, dto)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveReaction indicates an expected call of RemoveReaction.
func (mr *MockReactionsUseCasesMockRecorder) RemoveReaction(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReaction", reflect.TypeOf((*MockReactionsUseCases)(nil).RemoveReaction), ctx, dto)
}
