// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/settings_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,ChatsUseCases,MessagesUseCases,NotificationsUseCases,WebPushSubscriptionsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsUseCases is a mock of SettingsUseCases interface.
type MockSettingsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsUseCasesMockRecorder
	isgomock struct{}
}

// MockSettingsUseCasesMockRecorder is the mock recorder for MockSettingsUseCases.
type MockSettingsUseCasesMockRecorder struct {
	mock *MockSettingsUseCases
}

// NewMockSettingsUseCases creates a new mock instance.
func NewMockSettingsUseCases(ctrl *gomock.Controller) *MockSettingsUseCases {
	mock := &MockSettingsUseCases{ctrl: ctrl}
	mock.recorder = &MockSettingsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsUseCases) EXPECT() *MockSettingsUseCasesMockRecorder {
	return m.recorder
}

// GetSettingsByUserID mocks base method.
func (m *MockSettingsUseCases) GetSettingsByUserID(ctx context.Context, userID uint64) (*domains.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingsByUserID", ctx, userID)
	ret0, _ := ret[0].(*domains.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingsByUserID indicates an expected call of GetSettingsByUserID.
func (mr *MockSettingsUseCasesMockRecorder) GetSettingsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingsByUserID", reflect.TypeOf((*MockSettingsUseCases)(nil).GetSettingsByUserID), ctx, userID)
}

// UpdateSettings mocks base method.
func (m *MockSettingsUseCases) UpdateSettings(ctx context.Context, settings domains.Settings) (*domains.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, settings)
	ret0, _ := ret[0].(*domains.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSettingsUseCasesMockRecorder) UpdateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSettingsUseCases)(nil).UpdateSettings), ctx, settings)
}
