// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/users_usecases.go -package=mockusecases -exclude_interfaces=AuthUseCases,ChatsUseCases,MessagesUseCases,NotificationsUseCases,SettingsUseCases,WebPushSubscriptionsUseCases,FileStorageUseCases,ReactionsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	io "io"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersUseCases is a mock of UsersUseCases interface.
type MockUsersUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockUsersUseCasesMockRecorder
	isgomock struct{}
}

// MockUsersUseCasesMockRecorder is the mock recorder for MockUsersUseCases.
type MockUsersUseCasesMockRecorder struct {
	mock *MockUsersUseCases
}

// NewMockUsersUseCases creates a new mock instance.
func NewMockUsersUseCases(ctrl *gomock.Controller) *MockUsersUseCases {
	mock := &MockUsersUseCases{ctrl: ctrl}
	mock.recorder = &MockUsersUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersUseCases) EXPECT() *MockUsersUseCasesMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockUsersUseCases) DeleteAvatar(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockUsersUseCasesMockRecorder) DeleteAvatar(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockUsersUseCases)(nil).DeleteAvatar), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUsersUseCases) GetUserByID(ctx context.Context, id uint64) (*domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUsersUseCasesMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUsersUseCases)(nil).GetUserByID), ctx, id)
}

// GetUsers mocks base method.
func (m *MockUsersUseCases) GetUsers(ctx context.Context, filters *domains.UsersFilters, pagination *domains.Pagination) ([]domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, filters, pagination)
	ret0, _ := ret[0].([]domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUsersUseCasesMockRecorder) GetUsers(ctx, filters, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUsersUseCases)(nil).GetUsers), ctx, filters, pagination)
}

// UpdateAvatar mocks base method.
func (m *MockUsersUseCases) UpdateAvatar(ctx context.Context, userID uint64, data io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockUsersUseCasesMockRecorder) UpdateAvatar(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockUsersUseCases)(nil).UpdateAvatar), ctx, userID, data)
}

// UpdateUser mocks base method.
func (m *MockUsersUseCases) UpdateUser(ctx context.Context, userData domains.UpdateUserDTO) (*domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userData)
	ret0, _ := ret[0].(*domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsersUseCasesMockRecorder) UpdateUser(ctx, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsersUseCases)(nil).UpdateUser), ctx, userData)
}
