// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go
//
// Generated by this command:
//
//	mockgen -source=usecases.go -destination=../../mocks/usecases/web_push_subscriptions_usecases.go -package=mockusecases -exclude_interfaces=UsersUseCases,AuthUseCases,ChatsUseCases,MessagesUseCases,NotificationsUseCases,SettingsUseCases
//

// Package mockusecases is a generated GoMock package.
package mockusecases

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockWebPushSubscriptionsUseCases is a mock of WebPushSubscriptionsUseCases interface.
type MockWebPushSubscriptionsUseCases struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushSubscriptionsUseCasesMockRecorder
	isgomock struct{}
}

// MockWebPushSubscriptionsUseCasesMockRecorder is the mock recorder for MockWebPushSubscriptionsUseCases.
type MockWebPushSubscriptionsUseCasesMockRecorder struct {
	mock *MockWebPushSubscriptionsUseCases
}

// NewMockWebPushSubscriptionsUseCases creates a new mock instance.
func NewMockWebPushSubscriptionsUseCases(ctrl *gomock.Controller) *MockWebPushSubscriptionsUseCases {
	mock := &MockWebPushSubscriptionsUseCases{ctrl: ctrl}
	mock.recorder = &MockWebPushSubscriptionsUseCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushSubscriptionsUseCases) EXPECT() *MockWebPushSubscriptionsUseCasesMockRecorder {
	return m.recorder
}

// CreateWebPushSubscription mocks base method.
func (m *MockWebPushSubscriptionsUseCases) CreateWebPushSubscription(ctx context.Context, subscription domains.WebPushSubscription) (*domains.WebPushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebPushSubscription", ctx, subscription)
	ret0, _ := ret[0].(*domains.WebPushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebPushSubscription indicates an expected call of CreateWebPushSubscription.
func (mr *MockWebPushSubscriptionsUseCasesMockRecorder) CreateWebPushSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebPushSubscription", reflect.TypeOf((*MockWebPushSubscriptionsUseCases)(nil).CreateWebPushSubscription), ctx, subscription)
}

// DeleteWebPushSubscription mocks base method.
func (m *MockWebPushSubscriptionsUseCases) DeleteWebPushSubscription(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebPushSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebPushSubscription indicates an expected call of DeleteWebPushSubscription.
func (mr *MockWebPushSubscriptionsUseCasesMockRecorder) DeleteWebPushSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebPushSubscription", reflect.TypeOf((*MockWebPushSubscriptionsUseCases)(nil).DeleteWebPushSubscription), ctx, id)
}
