// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/chats_service.go -package=mockservices -exclude_interfaces=UsersService,AuthService,MessagesService,NotificationsService,SettingsService,WebPushSubscriptionsService,FileStorageService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsService is a mock of ChatsService interface.
type MockChatsService struct {
	ctrl     *gomock.Controller
	recorder *MockChatsServiceMockRecorder
	isgomock struct{}
}

// MockChatsServiceMockRecorder is the mock recorder for MockChatsService.
type MockChatsServiceMockRecorder struct {
	mock *MockChatsService
}

// NewMockChatsService creates a new mock instance.
func NewMockChatsService(ctrl *gomock.Controller) *MockChatsService {
	mock := &MockChatsService{ctrl: ctrl}
	mock.recorder = &MockChatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsService) EXPECT() *MockChatsServiceMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatsService) CreateChat(ctx context.Context, chat domains.Chat) (*domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chat)
	ret0, _ := ret[0].(*domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsServiceMockRecorder) CreateChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsService)(nil).CreateChat), ctx, chat)
}

// GetChatByID mocks base method.
func (m *MockChatsService) GetChatByID(ctx context.Context, chatID, userID uint64) (*domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatByID", ctx, chatID, userID)
	ret0, _ := ret[0].(*domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatByID indicates an expected call of GetChatByID.
func (mr *MockChatsServiceMockRecorder) GetChatByID(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatByID", reflect.TypeOf((*MockChatsService)(nil).GetChatByID), ctx, chatID, userID)
}

// GetChatMembers mocks base method.
func (m *MockChatsService) GetChatMembers(ctx context.Context, chatID, userID uint64) ([]domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembers", ctx, chatID, userID)
	ret0, _ := ret[0].([]domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembers indicates an expected call of GetChatMembers.
func (mr *MockChatsServiceMockRecorder) GetChatMembers(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembers", reflect.TypeOf((*MockChatsService)(nil).GetChatMembers), ctx, chatID, userID)
}

// GetUserChats mocks base method.
func (m *MockChatsService) GetUserChats(ctx context.Context, userID uint64, pagination *domains.Pagination) ([]domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", ctx, userID, pagination)
	ret0, _ := ret[0].([]domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatsServiceMockRecorder) GetUserChats(ctx, userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatsService)(nil).GetUserChats), ctx, userID, pagination)
}

// PrivateChatExists mocks base method.
func (m *MockChatsService) PrivateChatExists(ctx context.Context, members []domains.User) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateChatExists", ctx, members)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateChatExists indicates an expected call of PrivateChatExists.
func (mr *MockChatsServiceMockRecorder) PrivateChatExists(ctx, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateChatExists", reflect.TypeOf((*MockChatsService)(nil).PrivateChatExists), ctx, members)
}
