// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/messages_service.go -package=mockservices -exclude_interfaces=UsersService,AuthService,ChatsService,NotificationsService,SettingsService,WebPushSubscriptionsService,FileStorageService,ReactionsService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesService is a mock of MessagesService interface.
type MockMessagesService struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesServiceMockRecorder
	isgomock struct{}
}

// MockMessagesServiceMockRecorder is the mock recorder for MockMessagesService.
type MockMessagesServiceMockRecorder struct {
	mock *MockMessagesService
}

// NewMockMessagesService creates a new mock instance.
func NewMockMessagesService(ctrl *gomock.Controller) *MockMessagesService {
	mock := &MockMessagesService{ctrl: ctrl}
	mock.recorder = &MockMessagesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesService) EXPECT() *MockMessagesServiceMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessagesService) DeleteMessage(ctx context.Context, dto domains.DeleteMessageDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessagesServiceMockRecorder) DeleteMessage(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessagesService)(nil).DeleteMessage), ctx, dto)
}

// GetChatMessages mocks base method.
func (m *MockMessagesService) GetChatMessages(ctx context.Context, userID, chatID uint64, pagination *domains.Pagination) ([]domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessages", ctx, userID, chatID, pagination)
	ret0, _ := ret[0].([]domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessages indicates an expected call of GetChatMessages.
func (mr *MockMessagesServiceMockRecorder) GetChatMessages(ctx, userID, chatID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessages", reflect.TypeOf((*MockMessagesService)(nil).GetChatMessages), ctx, userID, chatID, pagination)
}

// GetMessageByID mocks base method.
func (m *MockMessagesService) GetMessageByID(ctx context.Context, userID, messageID uint64) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, userID, messageID)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessagesServiceMockRecorder) GetMessageByID(ctx, userID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessagesService)(nil).GetMessageByID), ctx, userID, messageID)
}

// GetUserUnreadCount mocks base method.
func (m *MockMessagesService) GetUserUnreadCount(ctx context.Context, userID uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUnreadCount", ctx, userID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserUnreadCount indicates an expected call of GetUserUnreadCount.
func (mr *MockMessagesServiceMockRecorder) GetUserUnreadCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUnreadCount", reflect.TypeOf((*MockMessagesService)(nil).GetUserUnreadCount), ctx, userID)
}

// SaveMessage mocks base method.
func (m *MockMessagesService) SaveMessage(ctx context.Context, message domains.Message) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessagesServiceMockRecorder) SaveMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessagesService)(nil).SaveMessage), ctx, message)
}

// UpdateMessage mocks base method.
func (m *MockMessagesService) UpdateMessage(ctx context.Context, dto domains.UpdateMessageDTO) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", ctx, dto)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockMessagesServiceMockRecorder) UpdateMessage(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockMessagesService)(nil).UpdateMessage), ctx, dto)
}
