// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/push_subscriptions_service.go -package=mockservices -exclude_interfaces=UsersService,AuthService,ChatsService,MessagesService,NotificationsService,SettingsService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockPushSubscriptionsService is a mock of PushSubscriptionsService interface.
type MockPushSubscriptionsService struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionsServiceMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionsServiceMockRecorder is the mock recorder for MockPushSubscriptionsService.
type MockPushSubscriptionsServiceMockRecorder struct {
	mock *MockPushSubscriptionsService
}

// NewMockPushSubscriptionsService creates a new mock instance.
func NewMockPushSubscriptionsService(ctrl *gomock.Controller) *MockPushSubscriptionsService {
	mock := &MockPushSubscriptionsService{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionsService) EXPECT() *MockPushSubscriptionsServiceMockRecorder {
	return m.recorder
}

// CreatePushSubscription mocks base method.
func (m *MockPushSubscriptionsService) CreatePushSubscription(ctx context.Context, subscription domains.PushSubscription) (*domains.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushSubscription", ctx, subscription)
	ret0, _ := ret[0].(*domains.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePushSubscription indicates an expected call of CreatePushSubscription.
func (mr *MockPushSubscriptionsServiceMockRecorder) CreatePushSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushSubscription", reflect.TypeOf((*MockPushSubscriptionsService)(nil).CreatePushSubscription), ctx, subscription)
}

// DeletePushSubscription mocks base method.
func (m *MockPushSubscriptionsService) DeletePushSubscription(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePushSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePushSubscription indicates an expected call of DeletePushSubscription.
func (mr *MockPushSubscriptionsServiceMockRecorder) DeletePushSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePushSubscription", reflect.TypeOf((*MockPushSubscriptionsService)(nil).DeletePushSubscription), ctx, id)
}

// DeletePushSubscriptionByEndpoint mocks base method.
func (m *MockPushSubscriptionsService) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePushSubscriptionByEndpoint", ctx, endpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePushSubscriptionByEndpoint indicates an expected call of DeletePushSubscriptionByEndpoint.
func (mr *MockPushSubscriptionsServiceMockRecorder) DeletePushSubscriptionByEndpoint(ctx, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePushSubscriptionByEndpoint", reflect.TypeOf((*MockPushSubscriptionsService)(nil).DeletePushSubscriptionByEndpoint), ctx, endpoint)
}

// GetPushSubscriptionsByUserID mocks base method.
func (m *MockPushSubscriptionsService) GetPushSubscriptionsByUserID(ctx context.Context, userID uint64) ([]domains.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domains.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushSubscriptionsByUserID indicates an expected call of GetPushSubscriptionsByUserID.
func (mr *MockPushSubscriptionsServiceMockRecorder) GetPushSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushSubscriptionsByUserID", reflect.TypeOf((*MockPushSubscriptionsService)(nil).GetPushSubscriptionsByUserID), ctx, userID)
}
