// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/reactions_service.go -package=mockservices -exclude_interfaces=UsersService,AuthService,ChatsService,MessagesService,NotificationsService,SettingsService,WebPushSubscriptionsService,FileStorageService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockReactionsService is a mock of ReactionsService interface.
type MockReactionsService struct {
	ctrl     *gomock.Controller
	recorder *MockReactionsServiceMockRecorder
	isgomock struct{}
}

// MockReactionsServiceMockRecorder is the mock recorder for MockReactionsService.
type MockReactionsServiceMockRecorder struct {
	mock *MockReactionsService
}

// NewMockReactionsService creates a new mock instance.
func NewMockReactionsService(ctrl *gomock.Controller) *MockReactionsService {
	mock := &MockReactionsService{ctrl: ctrl}
	mock.recorder = &MockReactionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReactionsService) EXPECT() *MockReactionsServiceMockRecorder {
	return m.recorder
}

// AddMessageReaction mocks base method.
func (m *MockReactionsService) AddMessageReaction(ctx context.Context, dto domains.MessageReactionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageReaction", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageReaction indicates an expected call of AddMessageReaction.
func (mr *MockReactionsServiceMockRecorder) AddMessageReaction(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageReaction", reflect.TypeOf((*MockReactionsService)(nil).AddMessageReaction), ctx, dto)
}

// GetReactionByID mocks base method.
func (m *MockReactionsService) GetReactionByID(ctx context.Context, id uint64) (*domains.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReactionByID", ctx, id)
	ret0, _ := ret[0].(*domains.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReactionByID indicates an expected call of GetReactionByID.
func (mr *MockReactionsServiceMockRecorder) GetReactionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReactionByID", reflect.TypeOf((*MockReactionsService)(nil).GetReactionByID), ctx, id)
}

// ListReactions mocks base method.
func (m *MockReactionsService) ListReactions(ctx context.Context) ([]domains.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReactions", ctx)
	ret0, _ := ret[0].([]domains.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReactions indicates an expected call of ListReactions.
func (mr *MockReactionsServiceMockRecorder) ListReactions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReactions", reflect.TypeOf((*MockReactionsService)(nil).ListReactions), ctx)
}

// ListReactionsForMessages mocks base method.
func (m *MockReactionsService) ListReactionsForMessages(ctx context.Context, messageIDs []uint64) (map[uint64][]domains.MessageReactionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReactionsForMessages", ctx, messageIDs)
	ret0, _ := ret[0].(map[uint64][]domains.MessageReactionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReactionsForMessages indicates an expected call of ListReactionsForMessages.
func (mr *MockReactionsServiceMockRecorder) ListReactionsForMessages(ctx, messageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReactionsForMessages", reflect.TypeOf((*MockReactionsService)(nil).ListReactionsForMessages), ctx, messageIDs)
}

// RemoveMessageReaction mocks base method.
func (m *MockReactionsService) RemoveMessageReaction(ctx context.Context, dto domains.MessageReactionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMessageReaction", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMessageReaction indicates an expected call of RemoveMessageReaction.
func (mr *MockReactionsServiceMockRecorder) RemoveMessageReaction(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMessageReaction", reflect.TypeOf((*MockReactionsService)(nil).RemoveMessageReaction), ctx, dto)
}
