// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/settings_service.go -package=mockservices -exclude_interfaces=AuthService,UsersService,ChatsService,MessagesService,NotificationsService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsService is a mock of SettingsService interface.
type MockSettingsService struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsServiceMockRecorder
	isgomock struct{}
}

// MockSettingsServiceMockRecorder is the mock recorder for MockSettingsService.
type MockSettingsServiceMockRecorder struct {
	mock *MockSettingsService
}

// NewMockSettingsService creates a new mock instance.
func NewMockSettingsService(ctrl *gomock.Controller) *MockSettingsService {
	mock := &MockSettingsService{ctrl: ctrl}
	mock.recorder = &MockSettingsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsService) EXPECT() *MockSettingsServiceMockRecorder {
	return m.recorder
}

// GetSettingsByUserID mocks base method.
func (m *MockSettingsService) GetSettingsByUserID(ctx context.Context, userID uint64) (*domains.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingsByUserID", ctx, userID)
	ret0, _ := ret[0].(*domains.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingsByUserID indicates an expected call of GetSettingsByUserID.
func (mr *MockSettingsServiceMockRecorder) GetSettingsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingsByUserID", reflect.TypeOf((*MockSettingsService)(nil).GetSettingsByUserID), ctx, userID)
}

// UpdateSettings mocks base method.
func (m *MockSettingsService) UpdateSettings(ctx context.Context, settings domains.Settings) (*domains.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, settings)
	ret0, _ := ret[0].(*domains.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSettingsServiceMockRecorder) UpdateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSettingsService)(nil).UpdateSettings), ctx, settings)
}
