// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=../../mocks/services/push_subscriptions_service.go -package=mockservices -exclude_interfaces=UsersService,AuthService,ChatsService,MessagesService,NotificationsService,SettingsService
//

// Package mockservices is a generated GoMock package.
package mockservices

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockWebPushSubscriptionsService is a mock of WebPushSubscriptionsService interface.
type MockWebPushSubscriptionsService struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushSubscriptionsServiceMockRecorder
	isgomock struct{}
}

// MockWebPushSubscriptionsServiceMockRecorder is the mock recorder for MockWebPushSubscriptionsService.
type MockWebPushSubscriptionsServiceMockRecorder struct {
	mock *MockWebPushSubscriptionsService
}

// NewMockWebPushSubscriptionsService creates a new mock instance.
func NewMockWebPushSubscriptionsService(ctrl *gomock.Controller) *MockWebPushSubscriptionsService {
	mock := &MockWebPushSubscriptionsService{ctrl: ctrl}
	mock.recorder = &MockWebPushSubscriptionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushSubscriptionsService) EXPECT() *MockWebPushSubscriptionsServiceMockRecorder {
	return m.recorder
}

// CreateWebPushSubscription mocks base method.
func (m *MockWebPushSubscriptionsService) CreateWebPushSubscription(ctx context.Context, subscription domains.WebPushSubscription) (*domains.WebPushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebPushSubscription", ctx, subscription)
	ret0, _ := ret[0].(*domains.WebPushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebPushSubscription indicates an expected call of CreateWebPushSubscription.
func (mr *MockWebPushSubscriptionsServiceMockRecorder) CreateWebPushSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebPushSubscription", reflect.TypeOf((*MockWebPushSubscriptionsService)(nil).CreateWebPushSubscription), ctx, subscription)
}

// DeleteWebPushSubscription mocks base method.
func (m *MockWebPushSubscriptionsService) DeleteWebPushSubscription(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebPushSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebPushSubscription indicates an expected call of DeleteWebPushSubscription.
func (mr *MockWebPushSubscriptionsServiceMockRecorder) DeleteWebPushSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebPushSubscription", reflect.TypeOf((*MockWebPushSubscriptionsService)(nil).DeleteWebPushSubscription), ctx, id)
}

// GetWebPushSubscriptionsByUserID mocks base method.
func (m *MockWebPushSubscriptionsService) GetWebPushSubscriptionsByUserID(ctx context.Context, userID uint64) ([]domains.WebPushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebPushSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domains.WebPushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebPushSubscriptionsByUserID indicates an expected call of GetWebPushSubscriptionsByUserID.
func (mr *MockWebPushSubscriptionsServiceMockRecorder) GetWebPushSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebPushSubscriptionsByUserID", reflect.TypeOf((*MockWebPushSubscriptionsService)(nil).GetWebPushSubscriptionsByUserID), ctx, userID)
}
