// Code generated by MockGen. DO NOT EDIT.
// Source: workers.go
//
// Generated by this command:
//
//	mockgen -source=workers.go -destination=../../mocks/workers/message_handler_builder.go -package=mockworkers -exclude_interfaces=
//

// Package mockworkers is a generated GoMock package.
package mockworkers

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/DKhorkov/kfc/internal/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageHandlerBuilder is a mock of MessageHandlerBuilder interface.
type MockMessageHandlerBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerBuilderMockRecorder
	isgomock struct{}
}

// MockMessageHandlerBuilderMockRecorder is the mock recorder for MockMessageHandlerBuilder.
type MockMessageHandlerBuilderMockRecorder struct {
	mock *MockMessageHandlerBuilder
}

// NewMockMessageHandlerBuilder creates a new mock instance.
func NewMockMessageHandlerBuilder(ctrl *gomock.Controller) *MockMessageHandlerBuilder {
	mock := &MockMessageHandlerBuilder{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandlerBuilder) EXPECT() *MockMessageHandlerBuilderMockRecorder {
	return m.recorder
}

// MessageHandler mocks base method.
func (m *MockMessageHandlerBuilder) MessageHandler(ctx context.Context) interfaces.MessageHandler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageHandler", ctx)
	ret0, _ := ret[0].(interfaces.MessageHandler)
	return ret0
}

// MessageHandler indicates an expected call of MessageHandler.
func (mr *MockMessageHandlerBuilderMockRecorder) MessageHandler(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageHandler", reflect.TypeOf((*MockMessageHandlerBuilder)(nil).MessageHandler), ctx)
}
