// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/chats_service.go -package=mockrepositories -exclude_interfaces=UsersRepository,AuthRepository,MessagesRepository,EmailsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsRepository is a mock of ChatsRepository interface.
type MockChatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatsRepositoryMockRecorder
	isgomock struct{}
}

// MockChatsRepositoryMockRecorder is the mock recorder for MockChatsRepository.
type MockChatsRepositoryMockRecorder struct {
	mock *MockChatsRepository
}

// NewMockChatsRepository creates a new mock instance.
func NewMockChatsRepository(ctrl *gomock.Controller) *MockChatsRepository {
	mock := &MockChatsRepository{ctrl: ctrl}
	mock.recorder = &MockChatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsRepository) EXPECT() *MockChatsRepositoryMockRecorder {
	return m.recorder
}

// ChangeChatIsReadStatus mocks base method.
func (m *MockChatsRepository) ChangeChatIsReadStatus(ctx context.Context, userID, chatID uint64, isRead bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeChatIsReadStatus", ctx, userID, chatID, isRead)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeChatIsReadStatus indicates an expected call of ChangeChatIsReadStatus.
func (mr *MockChatsRepositoryMockRecorder) ChangeChatIsReadStatus(ctx, userID, chatID, isRead any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeChatIsReadStatus", reflect.TypeOf((*MockChatsRepository)(nil).ChangeChatIsReadStatus), ctx, userID, chatID, isRead)
}

// CreateChat mocks base method.
func (m *MockChatsRepository) CreateChat(ctx context.Context, chat domains.Chat) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, chat)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsRepositoryMockRecorder) CreateChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsRepository)(nil).CreateChat), ctx, chat)
}

// GetChatByID mocks base method.
func (m *MockChatsRepository) GetChatByID(ctx context.Context, id uint64) (*domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatByID", ctx, id)
	ret0, _ := ret[0].(*domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatByID indicates an expected call of GetChatByID.
func (mr *MockChatsRepositoryMockRecorder) GetChatByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatByID", reflect.TypeOf((*MockChatsRepository)(nil).GetChatByID), ctx, id)
}

// GetChatMembers mocks base method.
func (m *MockChatsRepository) GetChatMembers(ctx context.Context, chatID uint64) ([]domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembers", ctx, chatID)
	ret0, _ := ret[0].([]domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembers indicates an expected call of GetChatMembers.
func (mr *MockChatsRepositoryMockRecorder) GetChatMembers(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembers", reflect.TypeOf((*MockChatsRepository)(nil).GetChatMembers), ctx, chatID)
}

// GetUserChats mocks base method.
func (m *MockChatsRepository) GetUserChats(ctx context.Context, userID uint64, pagination *domains.Pagination) ([]domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", ctx, userID, pagination)
	ret0, _ := ret[0].([]domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatsRepositoryMockRecorder) GetUserChats(ctx, userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatsRepository)(nil).GetUserChats), ctx, userID, pagination)
}
