// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/emails_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/khodfeltschat/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailsRepository is a mock of EmailsRepository interface.
type MockEmailsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailsRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailsRepositoryMockRecorder is the mock recorder for MockEmailsRepository.
type MockEmailsRepositoryMockRecorder struct {
	mock *MockEmailsRepository
}

// NewMockEmailsRepository creates a new mock instance.
func NewMockEmailsRepository(ctrl *gomock.Controller) *MockEmailsRepository {
	mock := &MockEmailsRepository{ctrl: ctrl}
	mock.recorder = &MockEmailsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailsRepository) EXPECT() *MockEmailsRepositoryMockRecorder {
	return m.recorder
}

// SendForgetPasswordMessage mocks base method.
func (m *MockEmailsRepository) SendForgetPasswordMessage(ctx context.Context, user domains.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendForgetPasswordMessage", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendForgetPasswordMessage indicates an expected call of SendForgetPasswordMessage.
func (mr *MockEmailsRepositoryMockRecorder) SendForgetPasswordMessage(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendForgetPasswordMessage", reflect.TypeOf((*MockEmailsRepository)(nil).SendForgetPasswordMessage), ctx, user)
}

// SendVerifyEmailMessage mocks base method.
func (m *MockEmailsRepository) SendVerifyEmailMessage(ctx context.Context, user domains.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerifyEmailMessage", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerifyEmailMessage indicates an expected call of SendVerifyEmailMessage.
func (mr *MockEmailsRepositoryMockRecorder) SendVerifyEmailMessage(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerifyEmailMessage", reflect.TypeOf((*MockEmailsRepository)(nil).SendVerifyEmailMessage), ctx, user)
}
