// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/file_storage_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository,EmailsRepository,MessagesRepository,ChatsRepository,SettingsRepository,WebPushSubscriptionsRepository,WebPushRepository,ReactionsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStorageRepository is a mock of FileStorageRepository interface.
type MockFileStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockFileStorageRepositoryMockRecorder is the mock recorder for MockFileStorageRepository.
type MockFileStorageRepositoryMockRecorder struct {
	mock *MockFileStorageRepository
}

// NewMockFileStorageRepository creates a new mock instance.
func NewMockFileStorageRepository(ctrl *gomock.Controller) *MockFileStorageRepository {
	mock := &MockFileStorageRepository{ctrl: ctrl}
	mock.recorder = &MockFileStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorageRepository) EXPECT() *MockFileStorageRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStorageRepository) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageRepositoryMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorageRepository)(nil).Delete), ctx, path)
}

// Download mocks base method.
func (m *MockFileStorageRepository) Download(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockFileStorageRepositoryMockRecorder) Download(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileStorageRepository)(nil).Download), ctx, path)
}

// Upload mocks base method.
func (m *MockFileStorageRepository) Upload(ctx context.Context, path string, data io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, path, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageRepositoryMockRecorder) Upload(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorageRepository)(nil).Upload), ctx, path, data)
}
