// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/push_subscriptions_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository,EmailsRepository,MessagesRepository,ChatsRepository,SettingsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockPushSubscriptionsRepository is a mock of PushSubscriptionsRepository interface.
type MockPushSubscriptionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPushSubscriptionsRepositoryMockRecorder
	isgomock struct{}
}

// MockPushSubscriptionsRepositoryMockRecorder is the mock recorder for MockPushSubscriptionsRepository.
type MockPushSubscriptionsRepositoryMockRecorder struct {
	mock *MockPushSubscriptionsRepository
}

// NewMockPushSubscriptionsRepository creates a new mock instance.
func NewMockPushSubscriptionsRepository(ctrl *gomock.Controller) *MockPushSubscriptionsRepository {
	mock := &MockPushSubscriptionsRepository{ctrl: ctrl}
	mock.recorder = &MockPushSubscriptionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushSubscriptionsRepository) EXPECT() *MockPushSubscriptionsRepositoryMockRecorder {
	return m.recorder
}

// CreatePushSubscription mocks base method.
func (m *MockPushSubscriptionsRepository) CreatePushSubscription(ctx context.Context, subscription domains.PushSubscription) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushSubscription", ctx, subscription)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePushSubscription indicates an expected call of CreatePushSubscription.
func (mr *MockPushSubscriptionsRepositoryMockRecorder) CreatePushSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushSubscription", reflect.TypeOf((*MockPushSubscriptionsRepository)(nil).CreatePushSubscription), ctx, subscription)
}

// DeletePushSubscription mocks base method.
func (m *MockPushSubscriptionsRepository) DeletePushSubscription(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePushSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePushSubscription indicates an expected call of DeletePushSubscription.
func (mr *MockPushSubscriptionsRepositoryMockRecorder) DeletePushSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePushSubscription", reflect.TypeOf((*MockPushSubscriptionsRepository)(nil).DeletePushSubscription), ctx, id)
}

// GetPushSubscriptionsByUserID mocks base method.
func (m *MockPushSubscriptionsRepository) GetPushSubscriptionsByUserID(ctx context.Context, userID uint64) ([]domains.PushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domains.PushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushSubscriptionsByUserID indicates an expected call of GetPushSubscriptionsByUserID.
func (mr *MockPushSubscriptionsRepositoryMockRecorder) GetPushSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushSubscriptionsByUserID", reflect.TypeOf((*MockPushSubscriptionsRepository)(nil).GetPushSubscriptionsByUserID), ctx, userID)
}
