// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/settings_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository,EmailsRepository,MessagesRepository,ChatsRepository,WebPushSubscriptionsRepository,WebPushRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepository is a mock of SettingsRepository interface.
type MockSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryMockRecorder is the mock recorder for MockSettingsRepository.
type MockSettingsRepositoryMockRecorder struct {
	mock *MockSettingsRepository
}

// NewMockSettingsRepository creates a new mock instance.
func NewMockSettingsRepository(ctrl *gomock.Controller) *MockSettingsRepository {
	mock := &MockSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepository) EXPECT() *MockSettingsRepositoryMockRecorder {
	return m.recorder
}

// CreateSettings mocks base method.
func (m *MockSettingsRepository) CreateSettings(ctx context.Context, settings domains.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSettings indicates an expected call of CreateSettings.
func (mr *MockSettingsRepositoryMockRecorder) CreateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSettings", reflect.TypeOf((*MockSettingsRepository)(nil).CreateSettings), ctx, settings)
}

// GetSettingsByUserID mocks base method.
func (m *MockSettingsRepository) GetSettingsByUserID(ctx context.Context, userID uint64) (*domains.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingsByUserID", ctx, userID)
	ret0, _ := ret[0].(*domains.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingsByUserID indicates an expected call of GetSettingsByUserID.
func (mr *MockSettingsRepositoryMockRecorder) GetSettingsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingsByUserID", reflect.TypeOf((*MockSettingsRepository)(nil).GetSettingsByUserID), ctx, userID)
}

// UpdateSettings mocks base method.
func (m *MockSettingsRepository) UpdateSettings(ctx context.Context, settings domains.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSettingsRepositoryMockRecorder) UpdateSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSettingsRepository)(nil).UpdateSettings), ctx, settings)
}
