// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/web_push_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository,EmailsRepository,MessagesRepository,ChatsRepository,SettingsRepository,WebPushSubscriptionsRepository,FileStorageRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockWebPushRepository is a mock of WebPushRepository interface.
type MockWebPushRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushRepositoryMockRecorder
	isgomock struct{}
}

// MockWebPushRepositoryMockRecorder is the mock recorder for MockWebPushRepository.
type MockWebPushRepositoryMockRecorder struct {
	mock *MockWebPushRepository
}

// NewMockWebPushRepository creates a new mock instance.
func NewMockWebPushRepository(ctrl *gomock.Controller) *MockWebPushRepository {
	mock := &MockWebPushRepository{ctrl: ctrl}
	mock.recorder = &MockWebPushRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushRepository) EXPECT() *MockWebPushRepositoryMockRecorder {
	return m.recorder
}

// SendNotification mocks base method.
func (m *MockWebPushRepository) SendNotification(ctx context.Context, subscription domains.WebPushSubscription, message domains.Message, unreadCount uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, subscription, message, unreadCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockWebPushRepositoryMockRecorder) SendNotification(ctx, subscription, message, unreadCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockWebPushRepository)(nil).SendNotification), ctx, subscription, message, unreadCount)
}
