// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/web_push_subscriptions_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository,EmailsRepository,MessagesRepository,ChatsRepository,SettingsRepository,WebPushRepository,FileStorageRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfc/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockWebPushSubscriptionsRepository is a mock of WebPushSubscriptionsRepository interface.
type MockWebPushSubscriptionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushSubscriptionsRepositoryMockRecorder
	isgomock struct{}
}

// MockWebPushSubscriptionsRepositoryMockRecorder is the mock recorder for MockWebPushSubscriptionsRepository.
type MockWebPushSubscriptionsRepositoryMockRecorder struct {
	mock *MockWebPushSubscriptionsRepository
}

// NewMockWebPushSubscriptionsRepository creates a new mock instance.
func NewMockWebPushSubscriptionsRepository(ctrl *gomock.Controller) *MockWebPushSubscriptionsRepository {
	mock := &MockWebPushSubscriptionsRepository{ctrl: ctrl}
	mock.recorder = &MockWebPushSubscriptionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushSubscriptionsRepository) EXPECT() *MockWebPushSubscriptionsRepositoryMockRecorder {
	return m.recorder
}

// CreateWebPushSubscription mocks base method.
func (m *MockWebPushSubscriptionsRepository) CreateWebPushSubscription(ctx context.Context, subscription domains.WebPushSubscription) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebPushSubscription", ctx, subscription)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebPushSubscription indicates an expected call of CreateWebPushSubscription.
func (mr *MockWebPushSubscriptionsRepositoryMockRecorder) CreateWebPushSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebPushSubscription", reflect.TypeOf((*MockWebPushSubscriptionsRepository)(nil).CreateWebPushSubscription), ctx, subscription)
}

// DeleteWebPushSubscription mocks base method.
func (m *MockWebPushSubscriptionsRepository) DeleteWebPushSubscription(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebPushSubscription", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebPushSubscription indicates an expected call of DeleteWebPushSubscription.
func (mr *MockWebPushSubscriptionsRepositoryMockRecorder) DeleteWebPushSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebPushSubscription", reflect.TypeOf((*MockWebPushSubscriptionsRepository)(nil).DeleteWebPushSubscription), ctx, id)
}

// GetWebPushSubscriptionsByUserID mocks base method.
func (m *MockWebPushSubscriptionsRepository) GetWebPushSubscriptionsByUserID(ctx context.Context, userID uint64) ([]domains.WebPushSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebPushSubscriptionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domains.WebPushSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebPushSubscriptionsByUserID indicates an expected call of GetWebPushSubscriptionsByUserID.
func (mr *MockWebPushSubscriptionsRepositoryMockRecorder) GetWebPushSubscriptionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebPushSubscriptionsByUserID", reflect.TypeOf((*MockWebPushSubscriptionsRepository)(nil).GetWebPushSubscriptionsByUserID), ctx, userID)
}
